language: haxe

os:
  - linux
  - osx

osx_image: xcode9.1
dist: trusty

haxe:
  - "3.4.4"
  - development

matrix:
  allow_failures:
    # Nothing should fail on development
    # - haxe: development

install:
  - haxelib install hxcpp
  - haxelib install hxcs
  - haxelib install hxjava
  - haxelib install run.hxml --always
  - haxelib dev dox .
  - haxelib list

script:
  - haxe run.hxml
  - haxe gen-test.hxml
  - haxe pages.hxml
