language: haxe

os:
  - linux
  - osx

osx_image: xcode9.1
dist: trusty

haxe:
  - 3.4.7
  - development

install:
  - haxelib install hxcpp
  - haxelib install hxcs
  - haxelib install hxjava
  - haxelib install run.hxml --always
  - haxelib git hxparse https://github.com/Simn/hxparse
  - haxelib dev dox .
  - haxelib list

script:
  - haxe run.hxml
  - haxe gen-test.hxml
  - haxe pages.hxml
