name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    strategy:
      matrix:
        haxe-version: [nightly, haxerc]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - if: matrix.haxe-version == 'nightly'
      run: |
        npx lix install haxe nightly
        npx lix install https://github.com/HaxeFoundation/hxcpp
        echo y | npx lix run hxcpp
    - run: npx haxe -cp .github/workflows --run RunCI
